import {
  LayoutDashboard,
  UserRound,
  WalletCards,
  Tags,
  ReceiptText,
  ChartNoAxesCombined,
  ShieldCheck,
  Flag,
  CreditCard,
  TrendingUp,
  TrendingDown,
  Settings2,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ArrowRight,
  Search,
  Plus,
  Pencil,
  Archive,
  ArchiveRestore,
  Trash2,
  Check,
  RefreshCw,
  AlertTriangle,
  CheckCircle2,
  Inbox,
  Target,
  Compass,
  PiggyBank,
  CalendarCheck,
  Landmark,
  Scale,
  SunMoon,
  Sun,
  Moon,
  Monitor,
  SlidersHorizontal,
  Bell,
  Download,
  ArrowDownLeft,
  ArrowUpRight,
  ArrowLeftRight,
  Building2,
  Banknote,
  ChartCandlestick,
  BriefcaseBusiness,
  Laptop,
  Percent,
  House,
  ShoppingBasket,
  HeartPulse,
  GraduationCap,
  Car,
  Zap,
  Utensils,
  Clapperboard,
  Gamepad2,
  ShoppingBag,
  Plane,
} from 'lucide-react'

// Single semantic name -> Lucide component mapping. Every consumer in the
// app references an icon by this short semantic key (e.g. "wallet"), never
// by importing a Lucide component directly — this is the one place the icon
// library is chosen, so every icon in the product shares one visual family.
const ICONS = {
  dashboard: LayoutDashboard,
  user: UserRound,
  wallet: WalletCards,
  tag: Tags,
  list: ReceiptText,
  barChart: ChartNoAxesCombined,
  shield: ShieldCheck,
  flag: Flag,
  creditCard: CreditCard,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: TrendingUp,
  settings: Settings2,
  logout: LogOut,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  search: Search,
  plus: Plus,
  pencil: Pencil,
  archive: Archive,
  archiveRestore: ArchiveRestore,
  trash: Trash2,
  check: Check,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle2,
  inbox: Inbox,
  target: Target,
  compass: Compass,
  piggyBank: PiggyBank,
  calendarCheck: CalendarCheck,
  landmark: Landmark,
  scale: Scale,
  sunMoon: SunMoon,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  sliders: SlidersHorizontal,
  bell: Bell,
  download: Download,
  arrowDownLeft: ArrowDownLeft,
  arrowUpRight: ArrowUpRight,
  arrowLeftRight: ArrowLeftRight,
  building: Building2,
  banknote: Banknote,
  chartCandlestick: ChartCandlestick,
  briefcase: BriefcaseBusiness,
  laptop: Laptop,
  percent: Percent,
  house: House,
  shoppingBasket: ShoppingBasket,
  heartPulse: HeartPulse,
  graduationCap: GraduationCap,
  car: Car,
  zap: Zap,
  utensils: Utensils,
  clapperboard: Clapperboard,
  gamepad: Gamepad2,
  shoppingBag: ShoppingBag,
  plane: Plane,
}

const Icon = ({ name, size = '1em', className = '', ...props }) => {
  const LucideIcon = ICONS[name]
  if (!LucideIcon) return null

  return <LucideIcon size={size} strokeWidth={1.75} className={className} aria-hidden="true" {...props} />
}

export default Icon
